Initial review for el9 aarch64 shim submission
ctrliq/ciq-shim-build pull request #4
Opened 2024-10-09 15:53 UTC by jason-rodri

WIP, will comment on items needing work 
Will tag on items needing review

2024-10-09 15:55 UTC, jason-rodri commented on Dockerfile
> +# Build and tag locally with:   docker build --tag ciq-shim-review:8 ./
update comment to reflect EL9

2024-10-09 16:13 UTC, jason-rodri commented on ciq_static_shim.repo
> +baseurl=https://dl.rockylinux.org/pub/rocky/$releasever/BaseOS/$basearch/kickstart/
hoping to update this once I can specify an older docker image

2025-01-02 23:29 UTC, josephtate commented
This is for all of CIQ's 9.x work, right? not just LTS 9.2?

2025-01-03 16:58 UTC, elguero commented
> This is for all of CIQ's 9.x work, right? not just LTS 9.2?

That is correct.  The SHIM can be used with all of 9.x.

2025-01-03 20:57 UTC, josephtate commented on README.md
> +CIQ shim-unsigned-x64 RPM repository:  [https://www.github.com/ctrliq/shim-unsigned-x64/src/ciq9/](https://github.com/ctrliq/shim-unsigned-x64/tree/ciq9)
We're doing Arm here, is this right?

2025-01-03 20:58 UTC, josephtate commented on README.md
> +baseurl=https://dl.rockylinux.org/vault/rocky/9.2/AppStream/x86_64/os/
Again, aarch64 vs x86_64?

2025-01-03 21:06 UTC, josephtate reviewed
I added some questions that made me scratch my head.

2025-01-03 21:06 UTC, josephtate commented on README.md
> +This is our first EL9 submission, we do not have old GRUB2 builds affected by CVEs.
This isn't the first 9 submission...

2025-01-03 21:06 UTC, josephtate commented on README.md
> +In the case of Grub + Fwupd, we will be running the same Rocky/RHEL versions unmodified, which also do not execute unauthenticated code by default.
Didn't we have to modify fwupd? Or was it just a rebuild.

2025-01-03 21:06 UTC, josephtate commented on README.md
> +We are also building and packaging supported upstream kernels designed for use on Rocky and enterprise-Linux variants.  These include supported LT versions (5.4, 5.10, 5.15, 6.1), as well as the roll
```suggestion
We are also building and packaging supported upstream kernels designed for use on Rocky and enterprise-Linux variants.  These include supported LT versions (5.4, 5.10, 5.15, 6.1), as well as the rolling latest-stable version.
```

2025-01-06 21:34 UTC, elguero commented on README.md
> +CIQ shim-unsigned-x64 RPM repository:  [https://www.github.com/ctrliq/shim-unsigned-x64/src/ciq9/](https://github.com/ctrliq/shim-unsigned-x64/tree/ciq9)
Yep, should say `shim-unsigned-aa64`

2025-01-06 21:35 UTC, elguero commented on README.md
> +In the case of Grub + Fwupd, we will be running the same Rocky/RHEL versions unmodified, which also do not execute unauthenticated code by default.
It was a rebuild from upstream for RL 9.

2025-01-06 21:35 UTC, elguero commented on README.md
> +This is our first EL9 submission, we do not have old GRUB2 builds affected by CVEs.
Correct.  Good catch.

2025-01-06 21:36 UTC, elguero commented on README.md
> +baseurl=https://dl.rockylinux.org/vault/rocky/9.2/AppStream/x86_64/os/
Good catch.  Should be `https://dl.rockylinux.org/vault/rocky/9.2/AppStream/aarch64/os/`

2025-01-09 18:01 UTC, josephtate commented on README.md
> +A temporary ephemral key is used to sign kernel modules
```suggestion
A temporary ephemeral key is used to sign kernel modules
```

2025-01-09 18:06 UTC, josephtate commented on README.md
> +CIQ shim-unsigned-x64 RPM repository:  [https://github.com/ctrliq/shim-unsigned-aa64/tree/ciq9](hhttps://github.com/ctrliq/shim-unsigned-aa64/tree/ciq9)
This still says x64, though the link is corrected.

2025-01-09 23:08 UTC, josephtate approved these changes
I don't have any other concerns.

2025-01-14 19:42 UTC, elguero requested changes

2025-01-14 19:42 UTC, elguero commented on README.md
> +- Position: Information Technology Director
My position has changed.

Principal Systems Engineer

2025-01-14 19:42 UTC, elguero commented on README.md
> +We are a new vendor for EL9, but I can confirm that our grub2 builds will not be affected by any of those, as they've all been fixed in our upstream:
I am not sure this statement is true anymore.  We are a new vendor for `aarch64` maybe?  Just caught my eye.

2025-01-14 19:42 UTC, elguero commented on README.md
> +shim.ciq,1,Ctrl IQ Inc,shim,15.8,mail:it_security@ciq.com
I believe the SBAT was updated to

![image](https://github.com/user-attachments/assets/cf18245c-e33c-41cc-8e49-f86ce372d217)

We might need to check into this one.

2025-01-14 19:42 UTC, elguero commented on README.md
> +shim.ciq,1,Ctrl IQ Inc,shim,15.8,mail:it_security@ciq.com
I think the shim package in the test repo needs to be updated.

The screen shot above is what is in the unsigned RPM package.

2025-01-14 21:36 UTC, elguero approved these changes
Looks great!

2025-01-14 21:39 UTC, merged